In [5]:
import numpy as np

transitionMatrix = np.array(
    (
        [0,0,0,0,0,0,1,1,0,0,1],
        [0.5,0,0,0,0,0,0,0,0,0,0],
        [0.5,0,0,0,0,0,0,0,0,0,0],
        [0,1,0,0,0,0,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0],
        [0,0,0,0,1,0,0,0,0.5,0,0],
        [0,0,0,0,0,0.5,0,0,0,0,0],
        [0,0,0,0,0,0.5,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0.5,0,0],
        [0,0,0,0,0,0,0,0,0,1,0],
    )
);


currentState = np.array(
    (
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    )
)


for i in range(0,20):
    print(f"state : {i + 1} | sum : {np.sum(currentState)}")
    currentState = np.matmul(transitionMatrix, currentState)
    
    print(currentState)



state : 1 | sum : 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
state : 2 | sum : 1.0
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
state : 3 | sum : 1.0
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
state : 4 | sum : 1.0
[0.  0.  0.  0.  0.  0.  0.5 0.5 0.  0.  0. ]
state : 5 | sum : 1.0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
state : 6 | sum : 1.0
[0.  0.5 0.5 0.  0.  0.  0.  0.  0.  0.  0. ]
state : 7 | sum : 1.0
[0.  0.  0.  0.5 0.  0.  0.  0.  0.  0.5 0. ]
state : 8 | sum : 1.0
[0.  0.  0.  0.  0.5 0.  0.  0.  0.  0.  0.5]
state : 9 | sum : 1.0
[0.5 0.  0.  0.  0.  0.5 0.  0.  0.  0.  0. ]
state : 10 | sum : 1.0
[0.   0.25 0.25 0.   0.   0.   0.25 0.25 0.   0.   0.  ]
state : 11 | sum : 1.0
[0.5  0.   0.   0.25 0.   0.   0.   0.   0.   0.25 0.  ]
state : 12 | sum : 1.0
[0.   0.25 0.25 0.   0.25 0.   0.   0.   0.   0.   0.25]
state : 13 | sum : 1.0
[0.25 0.   0.   0.25 0.   0.25 0.   0.   0.   0.25 0.  ]
state : 14 | sum : 1.0
[0.    0.125 0.125 0.    0.25  0.    0.125 0.125 0.    0.    0.25 ]
state : 15 | sum : 1.0
